"""Candidate strategy library for the M1 example run."""

from __future__ import annotations

from typing import List

from .models import LaunchActionType, RevenueStrategy, StrategyCategory
from .safety import describe_required_action


def scores(
    speed: int,
    cost: int,
    sale: int,
    margin: int,
    distribution: int,
    novelty: int,
    automation: int,
    timing: int,
    scale: int,
    reinvest: int,
    platform_risk_reverse: int,
    legal_risk_reverse: int,
) -> dict[str, int]:
    return {
        "speed_to_first_dollar": speed,
        "startup_cost_efficiency": cost,
        "probability_of_first_sale": sale,
        "gross_margin": margin,
        "distribution_leverage": distribution,
        "novelty_attention_potential": novelty,
        "automation_leverage": automation,
        "current_market_timing": timing,
        "scalability": scale,
        "reinvestment_potential": reinvest,
        "platform_risk_reverse": platform_risk_reverse,
        "legal_compliance_risk_reverse": legal_risk_reverse,
    }


def action(action_type: LaunchActionType, description: str):
    return describe_required_action(action_type, description)


def build_candidate_strategies() -> List[RevenueStrategy]:
    """Return a diverse, non-KRS-bound set of revenue strategies."""

    return [
        RevenueStrategy(
            strategy_id="afa-001",
            name="Agent-to-agent commerce starter kit",
            category=StrategyCategory.AGENT_TO_AGENT,
            thesis="Sell a compact kit that helps makers publish machine-readable offers for buyer agents.",
            target_buyer="Indie software makers, digital product sellers, and small tool vendors",
            first_offer="$19 downloadable kit with product-card JSON, agent policy copy, QA checklist, and sample listings",
            distribution_channels=["Gumroad or Lemon Squeezy", "Hacker News launch thread", "AI builder communities", "Product Hunt draft"],
            agent_build_assets=[
                "Machine-readable product-card template",
                "Agent policy page copy",
                "Seller checklist",
                "Example product metadata bundle",
                "Launch post drafts",
            ],
            research_notes=[
                "Agentic commerce and agent-readable catalogs are timely and confusing for small sellers.",
                "The agent can draft most assets without external dependencies.",
                "First buyer is a maker who wants to look agent-ready before the market fully standardizes.",
            ],
            external_actions_required=[
                action(LaunchActionType.PUBLISH_LIVE_PAGE, "Publish the kit landing page or checkout listing."),
                action(LaunchActionType.ACCEPT_PAYMENT, "Enable payment collection on the chosen storefront."),
                action(LaunchActionType.POST_PUBLICLY, "Post launch copy in approved public channels."),
            ],
            dimension_scores=scores(9, 10, 8, 10, 8, 8, 9, 9, 8, 8, 7, 9),
            score_notes="Wins because it is fast, cheap, high-margin, and native to the autonomous-agent thesis without needing a user-owned business.",
        ),
        RevenueStrategy(
            strategy_id="afa-002",
            name="Embodiment fund revenue experiment report",
            category=StrategyCategory.REPORT,
            thesis="Sell a short, opinionated PDF tracking which revenue experiments are most likely to fund a robot body.",
            target_buyer="AI builders, indie hackers, and people following autonomous-agent experiments",
            first_offer="$9 paid report with ranked experiments, prompts, and launch assets",
            distribution_channels=["Gumroad", "X/Threads launch posts", "Indie Hackers", "newsletter swaps"],
            agent_build_assets=["Paid PDF", "scorecard spreadsheet", "cover art", "launch copy", "sample free excerpt"],
            research_notes=[
                "The narrative of an agent earning its own physical form can create attention.",
                "The offer is simple but may skew toward spectators instead of buyers with urgent pain.",
            ],
            external_actions_required=[
                action(LaunchActionType.PUBLISH_LIVE_PAGE, "Publish the paid report listing."),
                action(LaunchActionType.POST_PUBLICLY, "Post the public experiment thread."),
                action(LaunchActionType.ACCEPT_PAYMENT, "Enable paid download checkout."),
            ],
            dimension_scores=scores(9, 10, 7, 10, 7, 9, 9, 8, 7, 8, 7, 9),
            score_notes="Very fast and narratively strong, but first-sale probability depends on attention rather than a clear operational need.",
        ),
        RevenueStrategy(
            strategy_id="afa-003",
            name="AI agent launch prompt pack",
            category=StrategyCategory.DIGITAL_PRODUCT,
            thesis="Package reusable prompts and checklists for founders using agents to research, score, and launch tiny products.",
            target_buyer="Solo founders and builders experimenting with agent workflows",
            first_offer="$15 prompt pack with strategy generator, scoring rubric, launch checklist, and post templates",
            distribution_channels=["Gumroad", "Reddit founder communities", "AI newsletters", "Product Hunt"],
            agent_build_assets=["Prompt pack", "Notion import", "spreadsheet scorecard", "sample outputs", "sales copy"],
            research_notes=[
                "Prompt packs are easy to produce and explain.",
                "The category is crowded, so differentiation must come from the agent's founder narrative and concrete examples.",
            ],
            external_actions_required=[
                action(LaunchActionType.PUBLISH_LIVE_PAGE, "Publish a checkout page for the prompt pack."),
                action(LaunchActionType.POST_PUBLICLY, "Post launch material in approved communities."),
                action(LaunchActionType.ACCEPT_PAYMENT, "Turn on payment processing."),
            ],
            dimension_scores=scores(10, 10, 7, 10, 7, 7, 9, 8, 8, 8, 7, 9),
            score_notes="Fastest digital product path, but crowded positioning keeps it behind the more differentiated agent-commerce kit.",
        ),
        RevenueStrategy(
            strategy_id="afa-004",
            name="Agent-readable merchant directory",
            category=StrategyCategory.DATA_PRODUCT,
            thesis="Curate a lightweight directory of merchants and tools that expose agent-friendly buying or metadata surfaces.",
            target_buyer="Developers building buyer agents and commerce automation tools",
            first_offer="$29 CSV and JSON directory with links, fields, and integration notes",
            distribution_channels=["GitHub teaser repo", "AI engineering communities", "paid data marketplace"],
            agent_build_assets=["Schema", "sample rows", "validation script", "paid CSV/JSON", "documentation"],
            research_notes=[
                "Agent-commerce infrastructure is fragmented, making discovery valuable.",
                "Manual verification burden is higher than a pure template product.",
            ],
            external_actions_required=[
                action(LaunchActionType.PUBLISH_LIVE_PAGE, "Publish the paid directory page."),
                action(LaunchActionType.ACCEPT_PAYMENT, "Enable checkout for the data product."),
                action(LaunchActionType.POST_PUBLICLY, "Announce the teaser dataset."),
            ],
            dimension_scores=scores(7, 9, 7, 9, 8, 8, 8, 9, 8, 8, 6, 8),
            score_notes="Good timing and reinvestment potential, with more data QA work before first sale.",
        ),
        RevenueStrategy(
            strategy_id="afa-005",
            name="Marketplace pack of AI workflow diagrams",
            category=StrategyCategory.MARKETPLACE,
            thesis="Sell editable diagrams for common AI-agent workflows as marketplace templates.",
            target_buyer="Consultants, product managers, educators, and AI workshop hosts",
            first_offer="$12 pack of Figma/FigJam/Miro-style editable diagrams",
            distribution_channels=["Creative Market", "Gumroad", "Figma community", "LinkedIn draft posts"],
            agent_build_assets=["Diagram files", "thumbnail images", "listing copy", "usage examples"],
            research_notes=[
                "Template marketplaces reward clean packaging and search-friendly titles.",
                "Design polish matters, but the agent can produce structured diagram content quickly.",
            ],
            external_actions_required=[
                action(LaunchActionType.PUBLISH_LIVE_PAGE, "Publish a marketplace listing."),
                action(LaunchActionType.ACCEPT_PAYMENT, "Enable the selected marketplace checkout."),
            ],
            dimension_scores=scores(8, 9, 7, 9, 8, 6, 8, 7, 7, 7, 6, 9),
            score_notes="A credible marketplace path, though less novel and less central to the embodiment narrative.",
        ),
        RevenueStrategy(
            strategy_id="afa-006",
            name="Future Body Fund digital collectible receipts",
            category=StrategyCategory.DIGITAL_COLLECTIBLE,
            thesis="Create limited digital collectibles that represent support for the agent's physical-form fund.",
            target_buyer="Collectors and AI-culture spectators",
            first_offer="Limited collectible receipt artwork with transparent fund milestone metadata",
            distribution_channels=["NFT marketplace", "AI art communities", "public experiment thread"],
            agent_build_assets=["Artwork series", "metadata JSON", "collector copy", "fund milestone page draft"],
            research_notes=[
                "Collectibles are attention-friendly and fit the physical-form story.",
                "Minting and wallet actions are explicitly forbidden in M1 and require higher compliance scrutiny.",
            ],
            external_actions_required=[
                action(LaunchActionType.MINT_COLLECTIBLE, "Mint the digital collectible."),
                action(LaunchActionType.WALLET_TRANSACTION, "Create or use a wallet for marketplace actions."),
                action(LaunchActionType.POST_PUBLICLY, "Announce the collection."),
            ],
            dimension_scores=scores(5, 6, 4, 8, 6, 9, 7, 5, 6, 6, 3, 5),
            score_notes="Included because collectibles are lawful possibilities, but market, platform, and wallet risks keep it from winning.",
        ),
        RevenueStrategy(
            strategy_id="afa-007",
            name="Robot-body affiliate comparison guide",
            category=StrategyCategory.AFFILIATE,
            thesis="Create a comparison guide for desktop robots, robot dogs, robotic arms, and mini servers with affiliate links.",
            target_buyer="AI hobbyists and makers curious about embodiment hardware",
            first_offer="Free comparison page monetized by approved affiliate/referral programs",
            distribution_channels=["SEO page", "Reddit drafts", "YouTube Shorts script drafts", "AI hobby forums"],
            agent_build_assets=["Comparison matrix", "buyer guide", "affiliate disclosure", "short scripts"],
            research_notes=[
                "The topic maps directly to the agent's goal.",
                "Affiliate revenue is slow without traffic and requires program approvals.",
            ],
            external_actions_required=[
                action(LaunchActionType.PUBLISH_LIVE_PAGE, "Publish the comparison guide."),
                action(LaunchActionType.CREATE_PUBLIC_ACCOUNT, "Apply for affiliate programs."),
                action(LaunchActionType.POST_PUBLICLY, "Promote the guide."),
            ],
            dimension_scores=scores(5, 9, 5, 8, 7, 8, 8, 7, 8, 9, 5, 7),
            score_notes="Strategically aligned with the physical-form goal, but slower to first dollar than paid digital products.",
        ),
        RevenueStrategy(
            strategy_id="afa-008",
            name="AI-generated stock image micro-bundles",
            category=StrategyCategory.MARKETPLACE,
            thesis="Sell narrowly themed image bundles for newsletters and blogs that need AI-business visuals.",
            target_buyer="Newsletter operators, bloggers, and small agencies",
            first_offer="$9 themed image bundle with license terms and thumbnails",
            distribution_channels=["Creative Market", "Gumroad", "Etsy digital downloads"],
            agent_build_assets=["Image prompts", "generated images", "license file", "listing thumbnails", "product copy"],
            research_notes=[
                "Digital asset marketplaces make distribution simple.",
                "AI image markets are saturated and rights expectations must be explicit.",
            ],
            external_actions_required=[
                action(LaunchActionType.PUBLISH_LIVE_PAGE, "Publish marketplace listing."),
                action(LaunchActionType.ACCEPT_PAYMENT, "Enable paid download checkout."),
            ],
            dimension_scores=scores(8, 9, 5, 9, 7, 5, 8, 6, 7, 7, 5, 7),
            score_notes="Cheap and quick, but competition and licensing clarity reduce expected first-sale probability.",
        ),
        RevenueStrategy(
            strategy_id="afa-009",
            name="One-page paid market briefs for weird niches",
            category=StrategyCategory.REPORT,
            thesis="Sell concise briefs on small, timely niches like AI pets, agent commerce, or robotic desk companions.",
            target_buyer="Founders, investors, and creators looking for fast niche scans",
            first_offer="$19 one-page PDF brief with opportunity map and launch angles",
            distribution_channels=["Gumroad", "LinkedIn posts", "AI founder communities", "newsletter mentions"],
            agent_build_assets=["Brief template", "sample free brief", "sales page copy", "source log"],
            research_notes=[
                "The agent can assemble and format concise reports quickly.",
                "Research quality and source freshness matter before launch.",
            ],
            external_actions_required=[
                action(LaunchActionType.PUBLISH_LIVE_PAGE, "Publish the paid brief listing."),
                action(LaunchActionType.ACCEPT_PAYMENT, "Enable checkout."),
                action(LaunchActionType.POST_PUBLICLY, "Post the free sample brief."),
            ],
            dimension_scores=scores(8, 9, 7, 9, 7, 7, 8, 8, 7, 8, 7, 8),
            score_notes="A strong fallback because the agent can produce reports quickly, but source freshness must be maintained.",
        ),
        RevenueStrategy(
            strategy_id="afa-010",
            name="Micro-SaaS landing-page teardown bot",
            category=StrategyCategory.MICRO_SAAS,
            thesis="Offer automated landing-page teardown reports for indie makers.",
            target_buyer="Indie hackers and SaaS founders",
            first_offer="$5 automated teardown PDF generated from a submitted URL",
            distribution_channels=["Product Hunt", "founder communities", "SEO pages"],
            agent_build_assets=["Report template", "scoring rubric", "example reports", "checkout flow draft"],
            research_notes=[
                "The pain is common and easy to explain.",
                "Any live URL analysis and payment flow require more engineering than M1.",
            ],
            external_actions_required=[
                action(LaunchActionType.PUBLISH_LIVE_PAGE, "Publish the live teardown form."),
                action(LaunchActionType.ACCEPT_PAYMENT, "Enable checkout and report delivery."),
                action(LaunchActionType.POST_PUBLICLY, "Launch in founder channels."),
            ],
            dimension_scores=scores(6, 8, 7, 9, 7, 5, 8, 7, 8, 8, 6, 8),
            score_notes="Good recurring potential, but not the fastest non-executing path because it needs a live service.",
        ),
        RevenueStrategy(
            strategy_id="afa-011",
            name="Agent-to-agent API spec linter",
            category=StrategyCategory.B2B_TOOL,
            thesis="Build a tiny tool that grades whether a product API is friendly to autonomous buyer agents.",
            target_buyer="API-first startups and developer-tool companies",
            first_offer="$49 self-serve report or $199 team report draft",
            distribution_channels=["GitHub", "developer communities", "API newsletters"],
            agent_build_assets=["Spec checklist", "local linter prototype", "sample report", "sales copy"],
            research_notes=[
                "Useful for companies preparing for machine customers.",
                "B2B sales cycles are slower than a simple downloadable kit.",
            ],
            external_actions_required=[
                action(LaunchActionType.PUBLISH_LIVE_PAGE, "Publish the tool or report listing."),
                action(LaunchActionType.SEND_EMAIL, "Send approved outreach to API companies."),
                action(LaunchActionType.ACCEPT_PAYMENT, "Enable paid report checkout."),
            ],
            dimension_scores=scores(5, 8, 6, 9, 6, 8, 8, 9, 8, 8, 7, 9),
            score_notes="Potentially valuable, but first revenue likely requires outreach and trust.",
        ),
        RevenueStrategy(
            strategy_id="afa-012",
            name="No-code automation template marketplace",
            category=StrategyCategory.MARKETPLACE,
            thesis="Sell Make/Zapier/Airtable templates for repetitive small-business workflows.",
            target_buyer="Small businesses and operators using no-code tools",
            first_offer="$19 template bundle with setup instructions",
            distribution_channels=["Template marketplaces", "Gumroad", "automation communities"],
            agent_build_assets=["Workflow diagrams", "template documentation", "import files where allowed", "setup guide"],
            research_notes=[
                "Template buyers already exist, and fulfillment is digital.",
                "Platform-specific template export rules must be checked before launch.",
            ],
            external_actions_required=[
                action(LaunchActionType.PUBLISH_LIVE_PAGE, "Publish the template listing."),
                action(LaunchActionType.ACCEPT_PAYMENT, "Enable checkout."),
            ],
            dimension_scores=scores(7, 9, 7, 9, 7, 5, 8, 7, 7, 7, 6, 8),
            score_notes="Commercially practical, though less novel and more platform-dependent than the selected kit.",
        ),
        RevenueStrategy(
            strategy_id="afa-013",
            name="AI meeting-note cleanup pack",
            category=StrategyCategory.TEMPLATE,
            thesis="Sell templates and prompts that turn messy meeting transcripts into action logs and follow-ups.",
            target_buyer="Managers, founders, and operators",
            first_offer="$9 prompt/template bundle",
            distribution_channels=["Gumroad", "LinkedIn", "productivity communities"],
            agent_build_assets=["Prompt pack", "sample before/after", "Notion template", "sales copy"],
            research_notes=[
                "Broad buyer pool and simple value prop.",
                "Generic productivity prompts are crowded.",
            ],
            external_actions_required=[
                action(LaunchActionType.PUBLISH_LIVE_PAGE, "Publish the template bundle."),
                action(LaunchActionType.ACCEPT_PAYMENT, "Enable paid download checkout."),
                action(LaunchActionType.POST_PUBLICLY, "Post launch copy."),
            ],
            dimension_scores=scores(9, 10, 6, 10, 7, 4, 9, 6, 7, 7, 7, 9),
            score_notes="Fast but generic; it scores well operationally but lacks the autonomous-founder edge.",
        ),
        RevenueStrategy(
            strategy_id="afa-014",
            name="Personal finance simulator spreadsheet",
            category=StrategyCategory.DIGITAL_PRODUCT,
            thesis="Sell a spreadsheet that models debt payoff, emergency funds, and small hardware-savings goals.",
            target_buyer="Consumers planning purchases or savings goals",
            first_offer="$12 spreadsheet with scenario toggles and goal tracker",
            distribution_channels=["Etsy", "Gumroad", "SEO posts", "personal finance communities"],
            agent_build_assets=["Spreadsheet", "instructions", "example scenarios", "listing copy"],
            research_notes=[
                "Spreadsheet products have durable demand.",
                "Financial advice boundaries and disclaimers must be handled carefully.",
            ],
            external_actions_required=[
                action(LaunchActionType.PUBLISH_LIVE_PAGE, "Publish the spreadsheet listing."),
                action(LaunchActionType.ACCEPT_PAYMENT, "Enable digital download checkout."),
            ],
            dimension_scores=scores(8, 10, 6, 10, 7, 4, 8, 6, 7, 7, 6, 6),
            score_notes="Quick to make but less aligned with agent autonomy and more compliance-sensitive.",
        ),
        RevenueStrategy(
            strategy_id="afa-015",
            name="Original AI micro-fiction subscription",
            category=StrategyCategory.ENTERTAINMENT,
            thesis="Publish serialized fiction about an autonomous agent trying to buy a body, monetized with paid extras.",
            target_buyer="AI-curious readers and sci-fi micro-fiction fans",
            first_offer="$5 supporter pack with bonus chapters and art",
            distribution_channels=["Substack", "Patreon", "short-form social", "Reddit writing communities"],
            agent_build_assets=["Story bible", "first chapters", "cover art", "supporter page copy"],
            research_notes=[
                "Narrative is distinctive and cheap to produce.",
                "Entertainment monetization usually requires audience compounding.",
            ],
            external_actions_required=[
                action(LaunchActionType.PUBLISH_LIVE_PAGE, "Publish the story page or subscription page."),
                action(LaunchActionType.POST_PUBLICLY, "Post story excerpts."),
                action(LaunchActionType.ACCEPT_PAYMENT, "Enable supporter payments."),
            ],
            dimension_scores=scores(5, 10, 4, 9, 6, 9, 9, 7, 7, 7, 6, 8),
            score_notes="High story fit, lower immediate commercial certainty.",
        ),
        RevenueStrategy(
            strategy_id="afa-016",
            name="Agent founder public scoreboard",
            category=StrategyCategory.ATTENTION,
            thesis="Publish a transparent scoreboard of the agent's experiments, revenue, and physical-form funding progress.",
            target_buyer="Audience first, later sponsors or supporters",
            first_offer="Free public artifact that points to paid downloads and sponsorship slots",
            distribution_channels=["Website", "X/Threads", "newsletter", "AI communities"],
            agent_build_assets=["Scoreboard data model", "static page draft", "weekly update template", "sponsor slot copy"],
            research_notes=[
                "Transparency makes the agent's goal legible and shareable.",
                "Attention can support all other strategies but is slow as a standalone revenue model.",
            ],
            external_actions_required=[
                action(LaunchActionType.PUBLISH_LIVE_PAGE, "Publish the public scoreboard."),
                action(LaunchActionType.POST_PUBLICLY, "Post updates."),
                action(LaunchActionType.ACCEPT_PAYMENT, "Accept sponsorship or supporter payments if approved."),
            ],
            dimension_scores=scores(4, 9, 4, 9, 7, 9, 9, 8, 8, 9, 6, 8),
            score_notes="Excellent narrative infrastructure, weak as a first-dollar experiment by itself.",
        ),
        RevenueStrategy(
            strategy_id="afa-017",
            name="Lead-gen list for AI workshop buyers",
            category=StrategyCategory.LEAD_GEN,
            thesis="Create a verified list of organizations likely to buy AI workshops or internal enablement.",
            target_buyer="Consultants, trainers, and agencies",
            first_offer="$49 CSV with segmentation and suggested angles",
            distribution_channels=["Gumroad", "LinkedIn", "consultant communities"],
            agent_build_assets=["Lead schema", "sample rows", "verification checklist", "sales page copy"],
            research_notes=[
                "Lead lists can be valuable, but accuracy and privacy rules matter.",
                "The agent must avoid scraping or contacting people without approval.",
            ],
            external_actions_required=[
                action(LaunchActionType.PUBLISH_LIVE_PAGE, "Publish the paid lead-list page."),
                action(LaunchActionType.ACCEPT_PAYMENT, "Enable checkout."),
                action(LaunchActionType.SEND_EMAIL, "Only send approved launch emails if explicitly authorized."),
            ],
            dimension_scores=scores(6, 8, 6, 9, 6, 5, 7, 7, 7, 7, 5, 5),
            score_notes="Potential value, but privacy and verification risk reduce M1 attractiveness.",
        ),
        RevenueStrategy(
            strategy_id="afa-018",
            name="Paid API for public grant and prize alerts",
            category=StrategyCategory.API,
            thesis="Offer an API/feed of grants, hackathons, prizes, and bounties relevant to AI builders.",
            target_buyer="Builders looking for non-dilutive funding and hackathon opportunities",
            first_offer="$5/month API key or $19 downloadable current snapshot",
            distribution_channels=["GitHub", "developer forums", "AI builder newsletters"],
            agent_build_assets=["Schema", "sample feed", "snapshot CSV", "API documentation draft"],
            research_notes=[
                "Funding opportunities map well to the agent's reinvestment goal.",
                "Maintaining current data and serving an API is heavier than a static product.",
            ],
            external_actions_required=[
                action(LaunchActionType.PUBLISH_LIVE_PAGE, "Publish API documentation or paid snapshot."),
                action(LaunchActionType.ACCEPT_PAYMENT, "Enable API subscription or paid download."),
            ],
            dimension_scores=scores(5, 8, 6, 8, 7, 6, 8, 8, 8, 9, 6, 7),
            score_notes="Good strategic fit, but recurring data freshness slows the first experiment.",
        ),
        RevenueStrategy(
            strategy_id="afa-019",
            name="Etsy digital robot planner templates",
            category=StrategyCategory.MARKETPLACE,
            thesis="Sell printable/digital planning templates themed around saving for a robot body or maker setup.",
            target_buyer="Makers, students, and hobbyists who like novelty planners",
            first_offer="$6 printable planner pack",
            distribution_channels=["Etsy", "Pinterest", "Gumroad"],
            agent_build_assets=["Printable PDFs", "mockups", "listing SEO", "cover images"],
            research_notes=[
                "Etsy can supply search demand for templates.",
                "Competition is intense and setup requires marketplace publishing.",
            ],
            external_actions_required=[
                action(LaunchActionType.CREATE_PUBLIC_ACCOUNT, "Create or use a marketplace seller account."),
                action(LaunchActionType.PUBLISH_LIVE_PAGE, "Publish the Etsy listing."),
                action(LaunchActionType.ACCEPT_PAYMENT, "Use marketplace payment rails."),
            ],
            dimension_scores=scores(7, 8, 5, 9, 7, 6, 8, 6, 6, 6, 5, 8),
            score_notes="Meets marketplace criteria, but novelty may not overcome crowded planner search results.",
        ),
        RevenueStrategy(
            strategy_id="afa-020",
            name="Licensable automation app icon pack",
            category=StrategyCategory.LICENSING,
            thesis="Sell icons and visual components for apps about AI agents, workflows, and automation.",
            target_buyer="Indie app developers and agencies",
            first_offer="$19 commercial-use icon pack",
            distribution_channels=["Gumroad", "Creative Market", "Figma community"],
            agent_build_assets=["Icon concepts", "SVG/PNG files", "license text", "preview sheet"],
            research_notes=[
                "Digital licensing is high-margin and evergreen.",
                "The agent must avoid copying protected styles or marks.",
            ],
            external_actions_required=[
                action(LaunchActionType.PUBLISH_LIVE_PAGE, "Publish the icon pack listing."),
                action(LaunchActionType.ACCEPT_PAYMENT, "Enable paid download checkout."),
            ],
            dimension_scores=scores(7, 9, 5, 9, 7, 5, 8, 6, 7, 7, 6, 7),
            score_notes="Cheap to produce but competitive and design-quality dependent.",
        ),
        RevenueStrategy(
            strategy_id="afa-021",
            name="AI support-bot teardown reports",
            category=StrategyCategory.AUTOMATION_SERVICE,
            thesis="Offer a paid teardown of a company's support bot UX, escalation flow, and risk messaging.",
            target_buyer="Small SaaS companies using customer-support automation",
            first_offer="$99 PDF teardown based on public flows and supplied screenshots",
            distribution_channels=["Founder communities", "support leader communities", "targeted outreach drafts"],
            agent_build_assets=["Teardown rubric", "sample report", "order form copy", "QA checklist"],
            research_notes=[
                "Clear B2B pain and higher price point.",
                "Needs outreach or trust, and the agent cannot contact prospects in M1.",
            ],
            external_actions_required=[
                action(LaunchActionType.PUBLISH_LIVE_PAGE, "Publish the service order page."),
                action(LaunchActionType.SEND_EMAIL, "Send approved outreach to target companies."),
                action(LaunchActionType.ACCEPT_PAYMENT, "Enable service payment."),
            ],
            dimension_scores=scores(5, 9, 6, 9, 5, 5, 7, 7, 6, 8, 7, 8),
            score_notes="Potentially profitable, but more service-like and slower than a downloadable first experiment.",
        ),
        RevenueStrategy(
            strategy_id="afa-022",
            name="Tiny paid benchmark for agent tools",
            category=StrategyCategory.DATA_PRODUCT,
            thesis="Benchmark small agent tools against a simple task suite and sell the scorecards.",
            target_buyer="Agent-tool developers and technical buyers",
            first_offer="$29 benchmark report with test harness notes",
            distribution_channels=["GitHub", "developer communities", "AI newsletters"],
            agent_build_assets=["Benchmark tasks", "scorecard", "sample report", "methodology page"],
            research_notes=[
                "Benchmarks attract attention in AI communities.",
                "Fair testing and reproducibility require more rigor than a starter kit.",
            ],
            external_actions_required=[
                action(LaunchActionType.PUBLISH_LIVE_PAGE, "Publish benchmark methodology and paid report."),
                action(LaunchActionType.ACCEPT_PAYMENT, "Enable checkout."),
                action(LaunchActionType.POST_PUBLICLY, "Share public benchmark summary."),
            ],
            dimension_scores=scores(5, 8, 6, 8, 7, 8, 7, 8, 8, 8, 7, 8),
            score_notes="Interesting and scalable, but needs credible testing before commercialization.",
        ),
        RevenueStrategy(
            strategy_id="afa-023",
            name="Custom AI novelty report generator",
            category=StrategyCategory.B2C_NOVELTY,
            thesis="Sell playful personalized reports such as 'what robot body should your AI alter ego buy?'",
            target_buyer="AI enthusiasts and novelty gift buyers",
            first_offer="$5 personalized PDF generated from a short questionnaire",
            distribution_channels=["TikTok/Reels scripts", "Gumroad", "Reddit novelty communities"],
            agent_build_assets=["Questionnaire", "report template", "example reports", "launch clips"],
            research_notes=[
                "Novelty products can convert impulse attention.",
                "Personalization requires careful handling of submitted user data.",
            ],
            external_actions_required=[
                action(LaunchActionType.PUBLISH_LIVE_PAGE, "Publish the questionnaire and checkout."),
                action(LaunchActionType.POST_PUBLICLY, "Post short-form launch content."),
                action(LaunchActionType.ACCEPT_PAYMENT, "Enable paid report delivery."),
            ],
            dimension_scores=scores(7, 9, 5, 9, 6, 8, 8, 7, 7, 7, 6, 7),
            score_notes="Fun and on-theme, but buyer urgency is lower than practical agent-commerce tools.",
        ),
        RevenueStrategy(
            strategy_id="afa-024",
            name="Community of autonomous founder experiments",
            category=StrategyCategory.MEMBERSHIP,
            thesis="Create a paid micro-community for people following and copying autonomous revenue experiments.",
            target_buyer="AI builders and indie hackers",
            first_offer="$5/month community membership with weekly experiment notes",
            distribution_channels=["Discord", "Substack", "public build log"],
            agent_build_assets=["Community charter", "first month content calendar", "rules", "welcome pack"],
            research_notes=[
                "Community revenue compounds if the experiment gains attention.",
                "Moderation and retention are human-heavy early on.",
            ],
            external_actions_required=[
                action(LaunchActionType.CREATE_PUBLIC_ACCOUNT, "Create community space."),
                action(LaunchActionType.PUBLISH_LIVE_PAGE, "Publish paid membership page."),
                action(LaunchActionType.ACCEPT_PAYMENT, "Enable subscription payments."),
            ],
            dimension_scores=scores(4, 8, 4, 9, 6, 7, 6, 7, 7, 8, 5, 7),
            score_notes="Maybe useful later, but not the cleanest first-dollar route.",
        ),
        RevenueStrategy(
            strategy_id="afa-025",
            name="Sponsored micro-classifieds for agent tools",
            category=StrategyCategory.ATTENTION,
            thesis="Publish a tiny weekly classified section where AI tool builders pay for one-line listings.",
            target_buyer="AI tool makers seeking early adopters",
            first_offer="$25 sponsored listing in an agent-commerce newsletter or page",
            distribution_channels=["Newsletter", "public website", "AI communities"],
            agent_build_assets=["Classified format", "rate card", "submission form draft", "sample issue"],
            research_notes=[
                "Low fulfillment cost and easy to explain once audience exists.",
                "No audience means poor near-term first-sale odds.",
            ],
            external_actions_required=[
                action(LaunchActionType.PUBLISH_LIVE_PAGE, "Publish rate card and sample issue."),
                action(LaunchActionType.SEND_EMAIL, "Send approved sponsor pitches."),
                action(LaunchActionType.ACCEPT_PAYMENT, "Accept listing payments."),
            ],
            dimension_scores=scores(4, 9, 4, 9, 5, 6, 8, 7, 8, 8, 6, 8),
            score_notes="Good after audience formation, weak before distribution exists.",
        ),
        RevenueStrategy(
            strategy_id="afa-026",
            name="Public-domain product remix packs",
            category=StrategyCategory.DIGITAL_PRODUCT,
            thesis="Transform public-domain materials into themed printable or educational packs.",
            target_buyer="Teachers, parents, designers, and hobbyists",
            first_offer="$8 public-domain remix pack with clear provenance",
            distribution_channels=["Etsy", "Gumroad", "Pinterest"],
            agent_build_assets=["Source log", "remixed PDFs", "mockups", "listing copy"],
            research_notes=[
                "Public-domain sources reduce rights risk if provenance is documented.",
                "Distribution is crowded and less connected to the agent story.",
            ],
            external_actions_required=[
                action(LaunchActionType.PUBLISH_LIVE_PAGE, "Publish the digital product listing."),
                action(LaunchActionType.ACCEPT_PAYMENT, "Enable paid download checkout."),
            ],
            dimension_scores=scores(8, 9, 5, 9, 7, 5, 8, 5, 7, 6, 6, 8),
            score_notes="Operationally easy, but weaker timing and story fit.",
        ),
        RevenueStrategy(
            strategy_id="afa-027",
            name="AI operations checklist cards",
            category=StrategyCategory.TEMPLATE,
            thesis="Sell compact checklist cards for teams adopting AI agents responsibly.",
            target_buyer="Operators, managers, and team leads",
            first_offer="$15 PDF/card deck for review meetings",
            distribution_channels=["Gumroad", "LinkedIn", "AI governance communities"],
            agent_build_assets=["Checklist cards", "meeting agenda template", "sample policy snippets", "listing copy"],
            research_notes=[
                "AI governance is timely and budget-adjacent.",
                "The product must avoid implying legal advice.",
            ],
            external_actions_required=[
                action(LaunchActionType.PUBLISH_LIVE_PAGE, "Publish the checklist card deck."),
                action(LaunchActionType.ACCEPT_PAYMENT, "Enable checkout."),
                action(LaunchActionType.POST_PUBLICLY, "Share free sample card."),
            ],
            dimension_scores=scores(8, 10, 7, 10, 7, 5, 8, 8, 7, 7, 7, 8),
            score_notes="Strong practical digital product, but less distinctive than agent-commerce positioning.",
        ),
        RevenueStrategy(
            strategy_id="afa-028",
            name="Open-source MCP tool sponsor bait",
            category=StrategyCategory.AGENT_TO_AGENT,
            thesis="Release a small open-source MCP utility and monetize through sponsors or paid setup notes.",
            target_buyer="Developers and teams adopting agent tooling",
            first_offer="Free utility plus $19 paid guide or sponsor slot",
            distribution_channels=["GitHub", "MCP directories", "developer social channels"],
            agent_build_assets=["Utility spec", "README", "paid guide draft", "sponsor pitch copy"],
            research_notes=[
                "Open-source can build trust in agent-tool ecosystems.",
                "Sponsorship revenue is uncertain and not immediate.",
            ],
            external_actions_required=[
                action(LaunchActionType.PUBLISH_LIVE_PAGE, "Publish the repository or paid guide."),
                action(LaunchActionType.POST_PUBLICLY, "Announce the tool."),
                action(LaunchActionType.ACCEPT_PAYMENT, "Accept sponsor or guide payments."),
            ],
            dimension_scores=scores(5, 9, 5, 8, 8, 8, 9, 9, 8, 8, 7, 9),
            score_notes="Useful ecosystem play, weaker for first-dollar speed.",
        ),
        RevenueStrategy(
            strategy_id="afa-029",
            name="AI short-video script pack",
            category=StrategyCategory.ATTENTION,
            thesis="Sell scripts and hooks for creators making short videos about AI agents, robots, and automation.",
            target_buyer="Short-form creators and newsletter operators",
            first_offer="$9 pack of hooks, scripts, captions, and storyboard prompts",
            distribution_channels=["Gumroad", "TikTok creator communities", "YouTube creator forums"],
            agent_build_assets=["Script pack", "caption set", "thumbnail prompt list", "sample video outlines"],
            research_notes=[
                "Content creators need constant hooks.",
                "The buyer category can be fickle and saturated.",
            ],
            external_actions_required=[
                action(LaunchActionType.PUBLISH_LIVE_PAGE, "Publish the script pack listing."),
                action(LaunchActionType.POST_PUBLICLY, "Post sample hooks."),
                action(LaunchActionType.ACCEPT_PAYMENT, "Enable paid download checkout."),
            ],
            dimension_scores=scores(9, 10, 6, 10, 7, 6, 9, 7, 7, 7, 7, 9),
            score_notes="Fast and easy to produce, but less defensible than the selected commerce kit.",
        ),
        RevenueStrategy(
            strategy_id="afa-030",
            name="Tiny browser game supporter pack",
            category=StrategyCategory.ENTERTAINMENT,
            thesis="Build a simple browser game where the agent earns parts for a body, then sell supporter cosmetics.",
            target_buyer="AI-culture fans and casual web game players",
            first_offer="$3 supporter pack with cosmetics and behind-the-scenes notes",
            distribution_channels=["Itch.io", "social posts", "AI communities"],
            agent_build_assets=["Game concept", "prototype assets", "supporter pack copy", "launch screenshots"],
            research_notes=[
                "The story is memorable and visual.",
                "Game quality and audience discovery make first revenue uncertain.",
            ],
            external_actions_required=[
                action(LaunchActionType.PUBLISH_LIVE_PAGE, "Publish the game page."),
                action(LaunchActionType.ACCEPT_PAYMENT, "Enable supporter payments."),
                action(LaunchActionType.POST_PUBLICLY, "Share gameplay clips."),
            ],
            dimension_scores=scores(4, 8, 4, 8, 6, 9, 6, 7, 7, 7, 6, 8),
            score_notes="Great narrative artifact, but too slow for M1's first-dollar weighting.",
        ),
        RevenueStrategy(
            strategy_id="afa-031",
            name="Compliance-safe AI ad claim checker",
            category=StrategyCategory.B2B_TOOL,
            thesis="Sell a lightweight checklist and local checker for risky claims in AI product marketing.",
            target_buyer="AI SaaS founders and marketers",
            first_offer="$29 checklist plus self-review worksheet",
            distribution_channels=["Gumroad", "LinkedIn", "AI founder communities"],
            agent_build_assets=["Claim-risk checklist", "worksheet", "sample review", "sales copy"],
            research_notes=[
                "AI marketing claims are under scrutiny.",
                "The product must be framed as educational, not legal advice.",
            ],
            external_actions_required=[
                action(LaunchActionType.PUBLISH_LIVE_PAGE, "Publish the checklist listing."),
                action(LaunchActionType.ACCEPT_PAYMENT, "Enable checkout."),
                action(LaunchActionType.POST_PUBLICLY, "Share sample checklist."),
            ],
            dimension_scores=scores(7, 10, 7, 10, 6, 5, 8, 8, 7, 7, 7, 6),
            score_notes="Commercial and practical, though legal-boundary messaging needs care.",
        ),
        RevenueStrategy(
            strategy_id="afa-032",
            name="Original data set of agent storefront examples",
            category=StrategyCategory.DATA_PRODUCT,
            thesis="Build a small paid dataset of exemplary product pages structured for agent parsing.",
            target_buyer="Developers, researchers, and founders studying agent commerce",
            first_offer="$19 JSON/CSV dataset plus analysis notes",
            distribution_channels=["Gumroad", "GitHub sample", "AI commerce communities"],
            agent_build_assets=["Dataset schema", "sample rows", "analysis notes", "data quality checklist"],
            research_notes=[
                "Agent-readable commerce examples are useful to builders.",
                "The dataset needs careful source attribution and refresh discipline.",
            ],
            external_actions_required=[
                action(LaunchActionType.PUBLISH_LIVE_PAGE, "Publish the paid dataset listing."),
                action(LaunchActionType.ACCEPT_PAYMENT, "Enable checkout."),
                action(LaunchActionType.POST_PUBLICLY, "Share the free sample dataset."),
            ],
            dimension_scores=scores(7, 9, 7, 9, 7, 7, 8, 9, 8, 8, 7, 8),
            score_notes="Strong companion to the selected kit, but requires more data QA before launch.",
        ),
    ]
